# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI #workflow

on: #จะถูกเรียกขึ้นมาทำงานก็ต่อเมื่อ เกิดeven เหล่านี้ มี2even
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ] # PR สามารถเกิดขึ้นมาได้หลาย banches

jobs:
  build: #จะทำการbluid ได้ก็ต่อเมื่อทำการต่างๆตามนี้นะ

    runs-on: ubuntu-latest #จะ run บนอะไร

    strategy:
      matrix: #เป็นการอยากจะtest แบบเลือกได้หลายๆ version 
        node-version: [12.x, 14.x] 

    steps:
    - uses: actions/checkout@v2 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci #เตรียมของ
    - run: npm run build --if-present #สร้างbluid ขึ้นมา
    - run: npm test
